name: "CI/CD"

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [10.x, 16.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
                cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm install 

            - name: Run Tests
              run: npm test
              
            - name: Build file
              run: npm run build
